server:
  port: 5000

spring:
  application:
    name: com.yang-common-api
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1000/eureka/
  instance:
    hostname: localhost
