server:
  port: 3000

spring:
  application:
    name: YANG-CROWD-REDIS
  redis:
    host: 192.168.234.128

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1000/eureka/



