server:
  port: 8000

spring:
  application:
    name: yang-crowd-order
  redis:
    host: 192.168.234.128
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1000/eureka/

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000